# Generated by Django 5.2.17 on 2026-08-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('confirmed_title', models.CharField(max_length=255)),
                ('confirmed_author', models.CharField(blank=True, max_length=255, null=True)),
                ('edition', models.CharField(blank=True, max_length=100, null=True)),
                ('source_match_confidence', models.FloatField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Library Book',
                'verbose_name_plural': 'Library Books',
                'ordering': ['-added_at'],
            },
        ),
    ]
