# Generated by Django 5.2.17 on 2026-08-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelfie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarybook',
            options={'ordering': ['-added_at', '-id'], 'verbose_name': 'Library Book', 'verbose_name_plural': 'Library Books'},
        ),
    ]
